### ISSUE TITLE
Best <3

### ISSUE THREAD

**Issue by sirxsniper** [patrykkolodziej/Explit#6]
Hello buddy, i really like what you do here ! I hope you will keep update it and add best features on it. Good job buddy. BTW menu look sick i love it but you need to adjust it somehow for every resolution. On my FULLHD it`s kinda small. Thank you again buddy and keep the good job. <3

**Comment by patrykkolodziej** [comment]
Change menu size here https://github.com/patrykkolodziej/Explit/blob/master/Explit/Explit/sdk/menu/menu.cpp#L8
Also probably you will need to adjust bigger font here https://github.com/patrykkolodziej/Explit/blob/master/Explit/Explit/sdk/hooks/hooks.cpp#L55

I can't adust it for bigger resolution because I'm using laptop with small screen.
